main: aufgabe1 aufgabe3

aufgabe1: racecondition.c semaph.c condsynchr.c
	gcc -pthread -o racecondition.out racecondition.c
	gcc -pthread -o semaph.out semaph.c
	gcc -pthread -o condsynchr.out condsynchr.c

aufgabe3: philosophers.c aufgabe3_2.c aufgabe3_3.c
	gcc -pthread -o philosophers.out philosophers.c
	gcc -pthread -o aufgabe3_2.out aufgabe3_2.c
	gcc -pthread -o aufgabe3_3.out aufgabe3_3.c
