main: aufgabe1 aufgabe3

aufgabe1: racecondition.c semaph.c condsynchr.c
	gcc -pthread -o racecondition.out racecondition.c
	gcc -pthread -o semaph.out semaph.c
	gcc -pthread -o condsynchr.out condsynchr.c

aufgabe3: philosophers.c
	gcc -pthread -o philosophers.out philosophers.c
