main: aufgabe1_1 reader writer aufgabe2_1

aufgabe1_1: aufgabe1_1.c
		gcc -o aufgabe1_1.out aufgabe1_1.c

reader: aufgabe1_2_reader.c
		gcc -o reader.out aufgabe1_2_reader.c

writer: aufgabe1_2_writer.c
		gcc -o writer.out aufgabe1_2_writer.c

aufgabe2_1: aufgabe2_1.c
		gcc -o aufgabe2_1.out aufgabe2_1.c
